#pragma once
enum class TiposToken{
  PALABRA_RESERVADA, 
  IDENTIFICADOR, 
  NUMERO_ENTERO, 
  CADENA,
  OPERADOR, 
  OPERADOR_ARITMETICO, 
  OPERADOR_LOGICO, 
  OPERADOR_RELACIONAL,
  OPERADOR_ASIGNACION,
  OPERADOR_ESPECIAL,
  PUNTO_COMA,
  COMA,
  PARENTESIS_IZQ,
  PARENTESIS_DER,
  LLAVE_IZQ,
};


